### ISSUE TITLE
Manipulate view

### ISSUE THREAD

**Issue by devloe** [amigold/FunDapter#14]
Is there a way to manipulate the view inside BindDictionary()?

Or how can I add an click event for a image view for instance? Can I do this inside BindDictionary function?

**Comment by dbachelder** [comment]
Like this?

```
myBindDict.addDynamicImageField(...).onClick(new ItemClickListener() {
  ...
}); 
```

**Comment by dbachelder** [comment]
@devyanlab I think that is your answer... if I misunderstood, please reopen!
