### ISSUE TITLE
Get view from BindDictionary

### ISSUE THREAD

**Issue by Mikelis** [amigold/FunDapter#16]
Hello! Can i get view from BindDictionary, for example there is visibilityIfNull, that can make my view invisible, but is there some mechanism, that in case that Integer is less than some threshold, i can make the TextView( with the integer number) red for example.

**Comment by amigold** [comment]
Hi!

For string fields you have the conditionalTextColor method which you can chain to the constructor call and do exactly what you're looking for

Hope it helps

**Comment by Mikelis** [comment]
I found a similiar question in stackoverflow, and while i was waiting i for the answer, I edited your libary for my porpose, you can see my answer here: 

http://stackoverflow.com/questions/23736826/fundapter-how-to-manipulate-the-view-layout/24161882#24161882
