### ISSUE TITLE
Multi listitem support?

### ISSUE THREAD

**Issue by johntheripp3r** [amigold/FunDapter#5]
It would be great if different list_item layouts can be specified for the same listview or any other view.

**Comment by amigold** [comment]
Good idea. How would you decide which layout to show for each item?

**Comment by johntheripp3r** [comment]
Hmmm... Thats the question. Create more than one BindDictionary and them for list item position somehow. Have you figured out any way?

**Comment by amigold** [comment]
Maybe the right way is to indeed allow the developer to create several BindDictionary objects and have a predicate that decides between them based on the position.

**Comment by johntheripp3r** [comment]
yeah thats it. That would be perfect

**Comment by Mikelis** [comment]
Use funDapter with https://github.com/commonsguy/cwac-merge , and make a wrapper adapter -  MergeAdapter and add as many FunDapters with diffrent layouts as you wish.

**Comment by dbachelder** [comment]
@Mikelis yeah, that works great. I do the same thing... I'm going to close this issue for now.
